# Constants_Sequences_and_Random_Values

In [0]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [0]:
from datetime import date
date.today()

datetime.date(2020, 3, 25)

In [0]:
tf.__version__

'1.15.0'

In [0]:
np.__version__

'1.18.2'

In [0]:
sess = tf.InteractiveSession()

/tensorflow-1.15.0/python3.6/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Constant Value Tensors

Q1. Create a tensor of the shape [2, 3] with all elements set to zero.


In [0]:
answer = tf.zeros([2,3])
answer.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

Q2. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to zero.

In [0]:
np_array = np.array([[1,2,3],[4,5,6]])
tf_array = tf.convert_to_tensor(np_array)
a = tf.zeros_like(tf_array)
a.eval()

array([[0, 0, 0],
       [0, 0, 0]])

Q3. Create a tensor of shape [2, 3] with all elements set to one.

In [0]:
tf_array = tf.ones([2,3])
tf_array.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Q4. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to one.

In [0]:
np_array = np.array([[1,2,3],[4,5,6]])
tf_array = tf.convert_to_tensor(np_array)
tf_array_final = tf.ones_like(tf_array)
tf_array_final.eval()

array([[1, 1, 1],
       [1, 1, 1]])

Q5. Create a tensor of the shape [3, 2], with all elements of 5.

In [0]:
tf_array = tf.zeros([3,2]) + 5
tf_array.eval()

array([[5., 5.],
       [5., 5.],
       [5., 5.]], dtype=float32)

Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]], with dtype=float32

In [0]:
tf_constant = tf.constant([[1,3,5],[4,6,8]], dtype = np.float32)
tf_constant.eval()

array([[1., 3., 5.],
       [4., 6., 8.]], dtype=float32)

Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.

In [0]:
tf_constant = tf.constant(np.ones([2,3])*4)
tf_constant.eval()

array([[4., 4., 4.],
       [4., 4., 4.]])

In [0]:
step = 1/50
np.arange(5,11,1/50)

array([ 5.  ,  5.02,  5.04,  5.06,  5.08,  5.1 ,  5.12,  5.14,  5.16,
        5.18,  5.2 ,  5.22,  5.24,  5.26,  5.28,  5.3 ,  5.32,  5.34,
        5.36,  5.38,  5.4 ,  5.42,  5.44,  5.46,  5.48,  5.5 ,  5.52,
        5.54,  5.56,  5.58,  5.6 ,  5.62,  5.64,  5.66,  5.68,  5.7 ,
        5.72,  5.74,  5.76,  5.78,  5.8 ,  5.82,  5.84,  5.86,  5.88,
        5.9 ,  5.92,  5.94,  5.96,  5.98,  6.  ,  6.02,  6.04,  6.06,
        6.08,  6.1 ,  6.12,  6.14,  6.16,  6.18,  6.2 ,  6.22,  6.24,
        6.26,  6.28,  6.3 ,  6.32,  6.34,  6.36,  6.38,  6.4 ,  6.42,
        6.44,  6.46,  6.48,  6.5 ,  6.52,  6.54,  6.56,  6.58,  6.6 ,
        6.62,  6.64,  6.66,  6.68,  6.7 ,  6.72,  6.74,  6.76,  6.78,
        6.8 ,  6.82,  6.84,  6.86,  6.88,  6.9 ,  6.92,  6.94,  6.96,
        6.98,  7.  ,  7.02,  7.04,  7.06,  7.08,  7.1 ,  7.12,  7.14,
        7.16,  7.18,  7.2 ,  7.22,  7.24,  7.26,  7.28,  7.3 ,  7.32,
        7.34,  7.36,  7.38,  7.4 ,  7.42,  7.44,  7.46,  7.48,  7.5 ,
        7.52,  7.54,

## Sequences

Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.

In [0]:
tf_array = tf.linspace(5.,10.,50)
tf_array.eval()

array([ 5.       ,  5.102041 ,  5.2040815,  5.3061223,  5.408163 ,
        5.5102043,  5.612245 ,  5.714286 ,  5.8163266,  5.9183674,
        6.020408 ,  6.122449 ,  6.2244897,  6.3265305,  6.4285717,
        6.5306125,  6.632653 ,  6.734694 ,  6.836735 ,  6.9387755,
        7.0408163,  7.142857 ,  7.244898 ,  7.346939 ,  7.44898  ,
        7.5510206,  7.6530614,  7.755102 ,  7.857143 ,  7.9591837,
        8.061225 ,  8.163265 ,  8.265306 ,  8.367347 ,  8.469388 ,
        8.571428 ,  8.67347  ,  8.775511 ,  8.877551 ,  8.979592 ,
        9.081633 ,  9.183674 ,  9.285714 ,  9.387755 ,  9.489796 ,
        9.591837 ,  9.693878 ,  9.795918 ,  9.89796  , 10.       ],
      dtype=float32)

Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].

In [0]:
tf_array = tf.range(10,102,2)
tf_array.eval()

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100], dtype=int32)

## Random Tensors

Q10. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=2.

In [0]:
tf_array = tf.random_normal([3,2],0,2)
tf_array.eval()

array([[ 3.330301  ,  0.30141428],
       [-4.5812874 ,  0.47159314],
       [ 0.57082874, -4.4772863 ]], dtype=float32)

Q11. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 such that any values don't exceed 2 standard deviations from the mean.

In [0]:
tf_array = tf.truncated_normal([3,2])
tf_array.eval()

array([[ 1.4827082 , -0.52188975],
       [-0.31008884,  1.5451634 ],
       [-0.6395897 , -0.6191088 ]], dtype=float32)

Q12. Create a random tensor of the shape [3, 2], with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).

In [0]:
tf_array = tf.random_uniform([3,2], 0, 2)
tf_array.eval()


array([[1.742218 , 1.551687 ],
       [1.6161773, 1.2491107],
       [1.9498134, 0.6859586]], dtype=float32)

Q13. Let X be a tensor of [[1, 2], [3, 4], [5, 6]]. Shuffle X along its first dimension.

In [0]:
array = np.array([[1,2],[3,4],[5,6]])
tf_array = tf.convert_to_tensor(array)
out = tf.random_shuffle(tf_array)
out.eval()

array([[5, 6],
       [3, 4],
       [1, 2]])

Q14. Let X be a random tensor of the shape [10, 10, 3], with elements from a unit normal distribution. Crop X with the shape of [5, 5, 3].

In [0]:
array = tf.random_uniform([10,10,3])
cropped_array = tf.random_crop(array, [5,5,3])
cropped_array.eval()

array([[[0.82225645, 0.7126162 , 0.5473341 ],
        [0.99407995, 0.63510203, 0.32453775],
        [0.3889904 , 0.23787332, 0.1596582 ],
        [0.05344427, 0.7890123 , 0.17584121],
        [0.5417594 , 0.67034185, 0.9253694 ]],

       [[0.5874196 , 0.10990787, 0.22874928],
        [0.63281167, 0.8928981 , 0.43607986],
        [0.88234556, 0.62071943, 0.93390095],
        [0.34247434, 0.77789736, 0.8213917 ],
        [0.07907379, 0.9691354 , 0.66736484]],

       [[0.99916565, 0.76610136, 0.3401332 ],
        [0.7787014 , 0.34238803, 0.7835252 ],
        [0.02795553, 0.9958525 , 0.12405252],
        [0.68296254, 0.7783307 , 0.7227143 ],
        [0.5150864 , 0.73871887, 0.75623584]],

       [[0.2799418 , 0.52360785, 0.04712784],
        [0.93851864, 0.2607535 , 0.55659294],
        [0.00814104, 0.50097716, 0.439942  ],
        [0.0053215 , 0.6446624 , 0.01543629],
        [0.37597156, 0.3429427 , 0.10240126]],

       [[0.21484995, 0.7749523 , 0.6869402 ],
        [0.8372936 , 0.207